"""Workflow redesign templates for healthcare AI transformation."""

from .models import WorkflowRedesign


def create_workflow_templates() -> list[WorkflowRedesign]:
    """Return 10 workflow redesign templates for healthcare."""
    return [
        WorkflowRedesign(
            workflow_name="Patient Intake",
            department="Administrative",
            current_steps=[
                {"step": "Patient arrives, waits at reception", "actor": "Patient", "time_mins": 5, "manual": True},
                {"step": "Receptionist collects demographics manually", "actor": "Receptionist", "time_mins": 10, "manual": True},
                {"step": "Paper forms completed by patient", "actor": "Patient", "time_mins": 15, "manual": True},
                {"step": "Receptionist enters data into system", "actor": "Receptionist", "time_mins": 10, "manual": True},
                {"step": "File created/retrieved from filing system", "actor": "Receptionist", "time_mins": 5, "manual": True},
                {"step": "Patient directed to waiting area", "actor": "Receptionist", "time_mins": 2, "manual": True},
            ],
            future_steps=[
                {"step": "Patient completes digital intake via app/tablet before arrival", "actor": "Patient/AI", "time_mins": 10, "ai_assisted": True},
                {"step": "AI validates and auto-populates system fields", "actor": "AI", "time_mins": 1, "ai_assisted": True},
                {"step": "AI flags missing info or anomalies for receptionist review", "actor": "AI", "time_mins": 1, "ai_assisted": True},
                {"step": "Receptionist resolves exceptions only", "actor": "Receptionist", "time_mins": 3, "ai_assisted": False},
                {"step": "Patient auto-checked in, directed by digital signage", "actor": "System", "time_mins": 1, "ai_assisted": True},
            ],
            time_savings_percent=65,
            annual_hours_saved=1560,
            implementation_cost=25000,
            tools_needed=["Digital intake platform", "AI data validation", "Patient portal/app"],
        ),
        WorkflowRedesign(
            workflow_name="Clinical Documentation",
            department="Clinical",
            current_steps=[
                {"step": "Clinician sees patient (consultation/care)", "actor": "Clinician", "time_mins": 20, "manual": False},
                {"step": "Clinician recalls key points post-consult", "actor": "Clinician", "time_mins": 5, "manual": True},
                {"step": "Clinician types progress notes into EHR", "actor": "Clinician", "time_mins": 15, "manual": True},
                {"step": "Clinician updates care plan manually", "actor": "Clinician", "time_mins": 10, "manual": True},
                {"step": "Clinician documents medications/orders", "actor": "Clinician", "time_mins": 5, "manual": True},
            ],
            future_steps=[
                {"step": "AI scribe listens during consultation (with consent)", "actor": "AI", "time_mins": 0, "ai_assisted": True},
                {"step": "Clinician sees patient (unchanged)", "actor": "Clinician", "time_mins": 20, "ai_assisted": False},
                {"step": "AI generates structured progress note draft", "actor": "AI", "time_mins": 1, "ai_assisted": True},
                {"step": "Clinician reviews and approves AI draft (edits as needed)", "actor": "Clinician", "time_mins": 3, "ai_assisted": True},
                {"step": "AI updates care plan with new observations", "actor": "AI + Clinician", "time_mins": 2, "ai_assisted": True},
            ],
            time_savings_percent=70,
            annual_hours_saved=3900,
            implementation_cost=35000,
            tools_needed=["AI medical scribe", "EHR integration", "Voice recognition"],
        ),
        WorkflowRedesign(
            workflow_name="Billing & Claims",
            department="Finance/Billing",
            current_steps=[
                {"step": "Coder reviews clinical documentation", "actor": "Coder", "time_mins": 15, "manual": True},
                {"step": "Coder selects billing codes (ICD-10, MBS, AN-ACC)", "actor": "Coder", "time_mins": 10, "manual": True},
                {"step": "Claim form prepared", "actor": "Billing Officer", "time_mins": 10, "manual": True},
                {"step": "Claim submitted to payer", "actor": "Billing Officer", "time_mins": 5, "manual": True},
                {"step": "Rejections reviewed and resubmitted manually", "actor": "Billing Officer", "time_mins": 20, "manual": True},
            ],
            future_steps=[
                {"step": "AI extracts codes from clinical documentation automatically", "actor": "AI", "time_mins": 2, "ai_assisted": True},
                {"step": "Coder validates AI-suggested codes", "actor": "Coder", "time_mins": 5, "ai_assisted": True},
                {"step": "AI pre-validates claim before submission", "actor": "AI", "time_mins": 1, "ai_assisted": True},
                {"step": "Automated claim submission", "actor": "System", "time_mins": 1, "ai_assisted": True},
                {"step": "AI auto-corrects common rejection reasons, flags complex ones", "actor": "AI + Billing Officer", "time_mins": 5, "ai_assisted": True},
            ],
            time_savings_percent=60,
            annual_hours_saved=1560,
            implementation_cost=30000,
            tools_needed=["AI coding assistant", "Claims validation engine", "EHR integration"],
        ),
        WorkflowRedesign(
            workflow_name="Staff Rostering",
            department="HR/Workforce",
            current_steps=[
                {"step": "Collect staff availability (phone/email/paper)", "actor": "Roster Officer", "time_mins": 60, "manual": True},
                {"step": "Check award conditions and care minute requirements", "actor": "Roster Officer", "time_mins": 30, "manual": True},
                {"step": "Build roster in spreadsheet/basic system", "actor": "Roster Officer", "time_mins": 120, "manual": True},
                {"step": "Distribute roster to staff", "actor": "Roster Officer", "time_mins": 15, "manual": True},
                {"step": "Handle swap requests and fill gaps manually", "actor": "Roster Officer", "time_mins": 60, "manual": True},
            ],
            future_steps=[
                {"step": "Staff submit availability via mobile app", "actor": "Staff/App", "time_mins": 5, "ai_assisted": True},
                {"step": "AI generates optimised roster meeting all constraints", "actor": "AI", "time_mins": 5, "ai_assisted": True},
                {"step": "Roster officer reviews and adjusts AI draft", "actor": "Roster Officer", "time_mins": 20, "ai_assisted": True},
                {"step": "Auto-notification to all staff via app", "actor": "System", "time_mins": 1, "ai_assisted": True},
                {"step": "AI handles swap requests within policy rules", "actor": "AI", "time_mins": 5, "ai_assisted": True},
            ],
            time_savings_percent=75,
            annual_hours_saved=1170,
            implementation_cost=40000,
            tools_needed=["AI rostering platform", "Mobile staff app", "Award interpretation engine"],
        ),
        WorkflowRedesign(
            workflow_name="Incident Reporting (SIRS)",
            department="Clinical",
            current_steps=[
                {"step": "Staff identifies reportable incident", "actor": "Staff", "time_mins": 0, "manual": False},
                {"step": "Paper incident form completed", "actor": "Staff", "time_mins": 15, "manual": True},
                {"step": "Form submitted to manager for review", "actor": "Manager", "time_mins": 10, "manual": True},
                {"step": "Manager investigates and documents findings", "actor": "Manager", "time_mins": 30, "manual": True},
                {"step": "SIRS notification prepared and submitted to Commission", "actor": "Compliance", "time_mins": 20, "manual": True},
                {"step": "Follow-up actions tracked manually", "actor": "Manager", "time_mins": 15, "manual": True},
            ],
            future_steps=[
                {"step": "Staff reports via mobile app with voice/text", "actor": "Staff/AI", "time_mins": 5, "ai_assisted": True},
                {"step": "AI classifies severity and SIRS reportability", "actor": "AI", "time_mins": 1, "ai_assisted": True},
                {"step": "AI pre-populates SIRS notification form", "actor": "AI", "time_mins": 2, "ai_assisted": True},
                {"step": "Manager reviews AI-drafted investigation", "actor": "Manager", "time_mins": 10, "ai_assisted": True},
                {"step": "Auto-submission to Commission within required timeframe", "actor": "System", "time_mins": 1, "ai_assisted": True},
                {"step": "AI tracks follow-up actions with automated reminders", "actor": "AI", "time_mins": 2, "ai_assisted": True},
            ],
            time_savings_percent=65,
            annual_hours_saved=780,
            implementation_cost=20000,
            tools_needed=["Digital incident reporting app", "SIRS integration", "AI classification engine"],
        ),
        WorkflowRedesign(
            workflow_name="Medication Management",
            department="Clinical",
            current_steps=[
                {"step": "Doctor prescribes medication (paper or basic e-prescribing)", "actor": "Doctor", "time_mins": 5, "manual": True},
                {"step": "Nurse checks medication chart manually", "actor": "Nurse", "time_mins": 5, "manual": True},
                {"step": "Nurse prepares and administers medication", "actor": "Nurse", "time_mins": 10, "manual": False},
                {"step": "Nurse signs medication chart", "actor": "Nurse", "time_mins": 2, "manual": True},
                {"step": "Controlled drugs: manual register entry", "actor": "Nurse x2", "time_mins": 5, "manual": True},
                {"step": "End of round: check for missed doses", "actor": "Nurse", "time_mins": 10, "manual": True},
            ],
            future_steps=[
                {"step": "Doctor e-prescribes with AI interaction checking", "actor": "Doctor/AI", "time_mins": 3, "ai_assisted": True},
                {"step": "AI validates against patient profile and alerts conflicts", "actor": "AI", "time_mins": 1, "ai_assisted": True},
                {"step": "Nurse scans patient and medication barcode", "actor": "Nurse/System", "time_mins": 2, "ai_assisted": True},
                {"step": "Nurse administers medication", "actor": "Nurse", "time_mins": 10, "ai_assisted": False},
                {"step": "AI auto-logs administration and updates controlled drug register", "actor": "AI", "time_mins": 0, "ai_assisted": True},
                {"step": "AI flags missed doses in real-time", "actor": "AI", "time_mins": 0, "ai_assisted": True},
            ],
            time_savings_percent=45,
            annual_hours_saved=1950,
            implementation_cost=45000,
            tools_needed=["Electronic medication management", "Barcode scanning", "AI interaction checker"],
        ),
        WorkflowRedesign(
            workflow_name="Quality & Compliance Reporting",
            department="Administrative",
            current_steps=[
                {"step": "Gather data from multiple systems manually", "actor": "Compliance Officer", "time_mins": 120, "manual": True},
                {"step": "Compile into report template", "actor": "Compliance Officer", "time_mins": 60, "manual": True},
                {"step": "Cross-reference against standards/requirements", "actor": "Compliance Officer", "time_mins": 60, "manual": True},
                {"step": "Identify gaps and prepare evidence", "actor": "Compliance Officer", "time_mins": 90, "manual": True},
                {"step": "Submit report to management/board", "actor": "Compliance Officer", "time_mins": 15, "manual": True},
            ],
            future_steps=[
                {"step": "AI auto-collects data from all connected systems", "actor": "AI", "time_mins": 5, "ai_assisted": True},
                {"step": "AI generates draft compliance report", "actor": "AI", "time_mins": 10, "ai_assisted": True},
                {"step": "AI highlights gaps with evidence mapping", "actor": "AI", "time_mins": 5, "ai_assisted": True},
                {"step": "Compliance officer reviews and finalises", "actor": "Compliance Officer", "time_mins": 30, "ai_assisted": True},
                {"step": "Auto-distribution to stakeholders", "actor": "System", "time_mins": 2, "ai_assisted": True},
            ],
            time_savings_percent=70,
            annual_hours_saved=1380,
            implementation_cost=30000,
            tools_needed=["AI compliance platform", "Data integration layer", "Automated reporting engine"],
        ),
        WorkflowRedesign(
            workflow_name="Clinical Handover",
            department="Clinical",
            current_steps=[
                {"step": "Outgoing nurse reviews each patient's notes", "actor": "Nurse", "time_mins": 20, "manual": True},
                {"step": "Outgoing nurse prepares verbal handover notes", "actor": "Nurse", "time_mins": 10, "manual": True},
                {"step": "Face-to-face handover meeting (bedside or office)", "actor": "Nurses x2", "time_mins": 30, "manual": True},
                {"step": "Incoming nurse documents key points", "actor": "Nurse", "time_mins": 10, "manual": True},
                {"step": "Incoming nurse verifies medications and care tasks", "actor": "Nurse", "time_mins": 10, "manual": True},
            ],
            future_steps=[
                {"step": "AI generates handover summary from shift data", "actor": "AI", "time_mins": 2, "ai_assisted": True},
                {"step": "AI highlights critical changes, overdue tasks, and alerts", "actor": "AI", "time_mins": 1, "ai_assisted": True},
                {"step": "Focused face-to-face handover on exceptions only", "actor": "Nurses x2", "time_mins": 15, "ai_assisted": True},
                {"step": "Incoming nurse reviews AI summary on mobile device", "actor": "Nurse", "time_mins": 5, "ai_assisted": True},
                {"step": "AI auto-verifies medication and task status", "actor": "AI", "time_mins": 1, "ai_assisted": True},
            ],
            time_savings_percent=55,
            annual_hours_saved=1170,
            implementation_cost=15000,
            tools_needed=["AI handover summary tool", "EHR integration", "Mobile handover app"],
        ),
        WorkflowRedesign(
            workflow_name="Family Communication",
            department="Clinical",
            current_steps=[
                {"step": "Family calls facility for update", "actor": "Receptionist", "time_mins": 5, "manual": True},
                {"step": "Receptionist finds relevant nurse", "actor": "Receptionist", "time_mins": 5, "manual": True},
                {"step": "Nurse provides verbal update", "actor": "Nurse", "time_mins": 10, "manual": True},
                {"step": "If needed, schedule family meeting", "actor": "Care Manager", "time_mins": 15, "manual": True},
                {"step": "Document communication in care record", "actor": "Nurse", "time_mins": 5, "manual": True},
            ],
            future_steps=[
                {"step": "Family accesses portal for daily AI-generated wellbeing update", "actor": "AI/Family", "time_mins": 0, "ai_assisted": True},
                {"step": "AI generates personalised weekly summary email", "actor": "AI", "time_mins": 1, "ai_assisted": True},
                {"step": "Nurse reviews and approves AI summary before sending", "actor": "Nurse", "time_mins": 3, "ai_assisted": True},
                {"step": "Video call scheduling via self-service portal", "actor": "Family/App", "time_mins": 2, "ai_assisted": True},
                {"step": "AI auto-documents all communications", "actor": "AI", "time_mins": 0, "ai_assisted": True},
            ],
            time_savings_percent=60,
            annual_hours_saved=624,
            implementation_cost=20000,
            tools_needed=["Family communication portal", "AI summary generator", "Video call platform"],
        ),
        WorkflowRedesign(
            workflow_name="Recruitment & Onboarding",
            department="HR/Workforce",
            current_steps=[
                {"step": "Write job ad and post to boards", "actor": "HR", "time_mins": 60, "manual": True},
                {"step": "Screen applications manually", "actor": "HR", "time_mins": 120, "manual": True},
                {"step": "Schedule interviews via email/phone", "actor": "HR", "time_mins": 30, "manual": True},
                {"step": "Conduct interviews and check references", "actor": "HR + Manager", "time_mins": 120, "manual": True},
                {"step": "Prepare onboarding pack (policies, forms)", "actor": "HR", "time_mins": 60, "manual": True},
                {"step": "New staff orientation (2-3 days)", "actor": "Various", "time_mins": 960, "manual": True},
            ],
            future_steps=[
                {"step": "AI generates job ad from role template", "actor": "AI + HR", "time_mins": 15, "ai_assisted": True},
                {"step": "AI screens and ranks applications", "actor": "AI", "time_mins": 10, "ai_assisted": True},
                {"step": "AI schedules interviews via self-service", "actor": "AI", "time_mins": 2, "ai_assisted": True},
                {"step": "AI-assisted structured interviews + reference checks", "actor": "HR + Manager + AI", "time_mins": 90, "ai_assisted": True},
                {"step": "AI-curated digital onboarding pathway", "actor": "AI", "time_mins": 5, "ai_assisted": True},
                {"step": "AI-guided orientation with progress tracking (1.5 days)", "actor": "AI + Various", "time_mins": 600, "ai_assisted": True},
            ],
            time_savings_percent=45,
            annual_hours_saved=390,
            implementation_cost=25000,
            tools_needed=["AI recruitment platform", "Digital onboarding system", "Learning management system"],
        ),
    ]

WORKFLOW_COUNT = 10
